- name: Create Lambda IAM role
  amazon.aws.iam_role:
    name: "{{ lambda_role_name }}"
    assume_role_policy_document: "{{ lookup('file', 'trust-policy.json') }}"

- name: Attach policy
  amazon.aws.iam_policy:
    iam_type: role
    iam_name: "{{ lambda_role_name }}"
    policy_name: lambda-policy
    policy_document: "{{ lookup('template', 'lambda-policy.json.j2') }}"
